package net.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.model.Bill;
import net.model.Customer;
import net.model.Movie;

/**
 *
 * @author NGUYEN KHAC TUAN
 */
public class BookTicketDialog extends javax.swing.JDialog implements ActionListener {

    private HomeFrm homeFrm;
    private Movie movie;
    private Customer customer;
    private Bill bill;
    private List<Customer> customers;
    private List<Bill> bills;
    private DefaultTableModel tableModelMovie;

    /**
     * Creates new form addMovieDialog
     */
    public BookTicketDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        addActionListener();
        homeFrm = (HomeFrm) parent;
    }

    public BookTicketDialog(java.awt.Frame parent, boolean modal,
            List<Customer> customers, Movie movie) {
        this(parent, modal);
        this.customers = customers;
        this.movie = movie;
        txtMovietIdReadOnly.setText(movie.getId() + "");
        txtMovieTypeReadOnly.setText(movie.getType());
        txtMovieNameReadOnly.setText(movie.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnShowBill = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCusIdReadOnly = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCusNameReadOnly = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCusTypeReadOnly = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMovieNameReadOnly = new javax.swing.JTextField();
        txtMovietIdReadOnly = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtBookTimeRO = new javax.swing.JTextField();
        txtMovieTypeReadOnly = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtMoviePriceReadOnly = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        btnInputBookTicket = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtNumOfTicket = new javax.swing.JTextField();
        btnBookTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ĐẶT VÉ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đặt vé phim");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Hủy bỏ");

        btnShowBill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnShowBill.setText("Xem hóa đơn");
        btnShowBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBillActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thanh toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã Khách hàng");

        txtCusIdReadOnly.setEditable(false);
        txtCusIdReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên ");

        txtCusNameReadOnly.setEditable(false);
        txtCusNameReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Đối tượng");

        txtCusTypeReadOnly.setEditable(false);
        txtCusTypeReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Mã phim");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tên phim");

        txtMovieNameReadOnly.setEditable(false);
        txtMovieNameReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMovietIdReadOnly.setEditable(false);
        txtMovietIdReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Thời gian đặt vé");

        txtBookTimeRO.setEditable(false);
        txtBookTimeRO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMovieTypeReadOnly.setEditable(false);
        txtMovieTypeReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Loại phim");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Tiền vé");

        txtMoviePriceReadOnly.setEditable(false);
        txtMoviePriceReadOnly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("     OC : khách hàng khác | SC : khách hàng học sinh/sinh viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel20))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(txtMoviePriceReadOnly)
                    .addComponent(txtMovieTypeReadOnly)
                    .addComponent(txtCusTypeReadOnly)
                    .addComponent(txtCusNameReadOnly)
                    .addComponent(txtCusIdReadOnly, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(txtMovietIdReadOnly)
                    .addComponent(txtMovieNameReadOnly)
                    .addComponent(txtBookTimeRO))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCusIdReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCusNameReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCusTypeReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtMovietIdReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMovieNameReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMovieTypeReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMoviePriceReadOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBookTimeRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Xóa dữ liệu");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhập liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Mã Khách hàng: ");

        txtCustomerId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnInputBookTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInputBookTicket.setText("Nhập");
        btnInputBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputBookTicketActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Số vé đặt:");

        txtNumOfTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumOfTicket.setText("1");

        btnBookTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBookTicket.setText("Đặt vé");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(txtNumOfTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtCustomerId)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInputBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBookTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumOfTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addComponent(btnInputBookTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnShowBill)
                .addGap(46, 46, 46)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowBill)
                    .addComponent(btnClear)
                    .addComponent(btnCancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowBillActionPerformed

    private void btnInputBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputBookTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputBookTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookTicketDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookTicketDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookTicketDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookTicketDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookTicketDialog dialog = new BookTicketDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInputBookTicket;
    private javax.swing.JButton btnShowBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtBookTimeRO;
    private javax.swing.JTextField txtCusIdReadOnly;
    private javax.swing.JTextField txtCusNameReadOnly;
    private javax.swing.JTextField txtCusTypeReadOnly;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtMovieNameReadOnly;
    private javax.swing.JTextField txtMoviePriceReadOnly;
    private javax.swing.JTextField txtMovieTypeReadOnly;
    private javax.swing.JTextField txtMovietIdReadOnly;
    private javax.swing.JTextField txtNumOfTicket;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnCancel)) {
            dispose();
        } else if (obj.equals(btnClear)) {
            clearData();
        } else if (obj.equals(btnInputBookTicket)) {
            if (txtNumOfTicket.getText().equalsIgnoreCase("")
                    || txtCustomerId.getText().equalsIgnoreCase("")) {
                var msg = "Vui lòng nhập đầy đủ thông tin!";
                showMessDialog(msg);
            } else {
                inputBookTicket();
            }
//            setCost();
        } else if (obj.equals(btnShowBill)) {
            if (txtBookTimeRO.getText().isEmpty()){
                var msg = "Vui lòng đặt vé trước khi xem hóa đơn!";
                showMessDialog(msg);
            } else {
                showBill();
            }
        } else if (obj.equals(btnBookTicket)) {
            addNewBooking();
        }
    }
//

    private void addActionListener() {
        btnBookTicket.addActionListener(this);
        btnCancel.addActionListener(this);
        btnClear.addActionListener(this);
        btnInputBookTicket.addActionListener(this);
        btnShowBill.addActionListener(this);
    }

    private void clearData() {
        var emptyText = "";
        txtCusIdReadOnly.setText(emptyText);
        txtCusNameReadOnly.setText(emptyText);
        txtCusTypeReadOnly.setText(emptyText);
        txtCustomerId.setText(emptyText);
//        txtMovieNameReadOnly.setText(emptyText);
        txtMoviePriceReadOnly.setText(emptyText);
//        txtMovieTypeReadOnly.setText(emptyText);
//        txtMovietIdReadOnly.setText(emptyText);
        txtBookTimeRO.setText(emptyText);
        txtNumOfTicket.setText(emptyText);
    }

    private void addNewBooking() {
        if (customer == null || txtNumOfTicket.getText().equalsIgnoreCase("")) {
            var msg = "Vui lòng nhập đủ thông tin";
            showMessDialog(msg);
        } else {
            var currentTime = new Date();
            var format = "dd/MM/yyyy HH:mm:ss";
            var dateFormat = new SimpleDateFormat(format);
            txtBookTimeRO.setText(dateFormat.format(currentTime));
            var priceTicket = Long.parseLong(txtMoviePriceReadOnly.getText());
            var numOfTicket = Integer.parseInt(txtNumOfTicket.getText());
            Bill b = new Bill(customer, movie, currentTime,
                    priceTicket, numOfTicket);
            homeFrm.addBookingCallback(b);
            var msg = "Đặt vé và lưu hóa đơn thành công!";
            showMessDialog(msg);
        }
    }

    private Bill addShowDetailedBill() {
        var currentTime = new Date();
        var format = "dd/MM/yyyy HH:mm:ss";
        var dateFormat = new SimpleDateFormat(format);
        txtBookTimeRO.setText(dateFormat.format(currentTime));
        var priceTicket = Long.parseLong(txtMoviePriceReadOnly.getText());
        var numOfTicket = Integer.parseInt(txtNumOfTicket.getText());
        Bill b = new Bill(customer, movie, currentTime,
                priceTicket, numOfTicket);
        return b;
    }

    private void inputBookTicket() {
        customer = null;
        var emptyText = "";
        var customerId = txtCustomerId.getText().trim();
        if (customerId.isEmpty()) {
            var msg = "Vui lòng nhập mã khách hàng cần tìm!";
            showMessDialog(msg);
        } else {
            for (Customer c : customers) {
                if (c.getId().compareToIgnoreCase(customerId) == 0) {
                    customer = c;
                    break;
                }
            }

            if (customer != null) {
                txtCusIdReadOnly.setText(customer.getId());
                txtCusNameReadOnly.setText(customer.getFullName());
                txtCusTypeReadOnly.setText(customer.getCustomerType());
                setCost();
            } else {
                txtCusIdReadOnly.setText(emptyText);
                txtCusNameReadOnly.setText(emptyText);
                txtCusTypeReadOnly.setText(emptyText);
                var msg = "Khách hàng cần tìm hiện "
                        + "không tồn tại. Vui lòng thử lại!";
                showMessDialog(msg);
            }
        }
    }

    private void showBill() {
        ShowDetailedBill showDetailedBill = new ShowDetailedBill(this, 
                rootPaneCheckingEnabled, addShowDetailedBill());
        showDetailedBill.setVisible(true);
    }

    private void showMessDialog(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }

    private void setCost() { // chỗ này cần sửa
        var roomType = txtMovieTypeReadOnly.getText();
        var cusType = txtCusTypeReadOnly.getText();
        int room2DPriceOC = 70000;
        int room2DPriceSC = 50000;
        int room3DPriceOC = 100000;
        int room3DPriceSC = 70000;
        int room4DPrice = 150000;
        var nOB = Integer.parseInt(txtNumOfTicket.getText());
        if (roomType.equalsIgnoreCase("4D")) {
            var price = nOB * room4DPrice;
            txtMoviePriceReadOnly.setText(price + "");
        }

        if (cusType.equalsIgnoreCase("OC")) {
            if (roomType.equalsIgnoreCase("2D")) {
                var price = nOB * room2DPriceOC;
                txtMoviePriceReadOnly.setText(price + "");
            } else if (roomType.equalsIgnoreCase("3D")) {
                var price = nOB * room3DPriceOC;
                txtMoviePriceReadOnly.setText(price + "");
            }
        } else if (cusType.equalsIgnoreCase("SC")) {
            if (roomType.equalsIgnoreCase("2D")) {
                var price = nOB * room2DPriceSC;
                txtMoviePriceReadOnly.setText(price + "");
            } else if (roomType.equalsIgnoreCase("3D")) {
                var price = nOB * room3DPriceSC;
                txtMoviePriceReadOnly.setText(price + "");
            }
        }
    }
}
